import { ArabicCurriculumLevel } from "@/constants/Types";

export const arabicCurriculum: ArabicCurriculumLevel[] = [
  {
    id: "1",
    title: "Buchstaben kennenlernen",
    shortTitle: "Level 1",
    description:
      "In diesem Level lernst du die wichtigsten arabischen Buchstaben kennen. Du erkennst, dass viele Buchstaben ähnlich aussehen und sich oft nur durch ihre Punkte unterscheiden.",
    modules: [
      "Einfache einzelne Buchstaben",
      "Buchstaben mit ähnlicher Form",
      "Weitere wichtige Buchstabengruppen",
    ],
  },
  {
    id: "2",
    title: "Buchstaben in Wörtern erkennen",
    shortTitle: "Level 2",
    description:
      "Hier lernst du, wie Buchstaben im Wort aussehen. Du erkennst, dass ein Buchstabe je nach Position am Anfang, in der Mitte oder am Ende anders aussehen kann.",
    modules: [
      "Einzel- und Endform",
      "Anfangs- und Mittelform",
      "Buchstabenformen vergleichen",
    ],
  },
  {
    id: "3",
    title: "Buchstaben verbinden",
    shortTitle: "Level 3",
    description:
      "In diesem Level verstehst du, wie Buchstaben miteinander verbunden werden. Du lernst auch, dass manche Buchstaben eine Verbindung unterbrechen.",
    modules: [
      "Verbundene und nicht verbundene Buchstaben",
      "Zwei- und Dreierverbindungen",
      "Erste kleine Wörter",
    ],
  },
  {
    id: "4",
    title: "Kurze Vokale lesen",
    shortTitle: "Level 4",
    description:
      "Jetzt beginnst du richtig zu lesen. Du lernst die kurzen Vokale kennen und kannst erste einfache Silben und Wörter mit Vokalzeichen lesen.",
    modules: ["Fatḥa", "Kasra und Ḍamma", "Erste Wörter mit Vokalzeichen"],
  },
  {
    id: "5",
    title: "Lange Vokale lesen",
    shortTitle: "Level 5",
    description:
      "Hier lernst du den Unterschied zwischen kurzen und langen Vokalen. Dadurch kannst du Wörter sicherer und genauer lesen.",
    modules: ["ā", "ī und ū", "Training mit kurzen und langen Vokalen"],
  },
  {
    id: "6",
    title: "Wichtige Lesezeichen verstehen",
    shortTitle: "Level 6",
    description:
      "In diesem Level lernst du weitere wichtige Zeichen kennen, die beim Lesen helfen. So kannst du häufige Wortmuster und schwierigere Wörter besser verstehen.",
    modules: ["Sukūn", "Shadda", "Tanwīn und häufige Wortmuster"],
  },
  {
    id: "7",
    title: "Kurze religiöse Texte lesen",
    shortTitle: "Level 7",
    description:
      "Zum Schluss wendest du alles Gelernte auf religiöse Wörter und kurze Texte an. Du liest erste Duʿāʾ-Formeln und sehr kurze qurʾānnahe Passagen.",
    modules: [
      "Wichtige religiöse Wörter",
      "Bekannte Formeln und kurze Duʿāʾ",
      "Sehr kurze qurʾānnahe Texte",
    ],
  },
];


export const arabicLetters = [
  {
    letter: "ا",
    name: "Alif",
    pronunciation: "wie ein langes a",
    isolated: "ا",
    initial: "ا",
    medial: "ـا",
    final: "ـا",
  },
  {
    letter: "ب",
    name: "Bāʾ",
    pronunciation: "wie b in Ball",
    isolated: "ب",
    initial: "بـ",
    medial: "ـبـ",
    final: "ـب",
  },
  {
    letter: "ت",
    name: "Tāʾ",
    pronunciation: "wie t in Tag",
    isolated: "ت",
    initial: "تـ",
    medial: "ـتـ",
    final: "ـت",
  },
  {
    letter: "ث",
    name: "Thāʾ",
    pronunciation: "wie th in think",
    isolated: "ث",
    initial: "ثـ",
    medial: "ـثـ",
    final: "ـث",
  },
  {
    letter: "ج",
    name: "Jīm",
    pronunciation: "wie dsch in Dschungel",
    isolated: "ج",
    initial: "جـ",
    medial: "ـجـ",
    final: "ـج",
  },
  {
    letter: "ح",
    name: "Ḥāʾ",
    pronunciation: "ein starkes h aus dem Hals",
    isolated: "ح",
    initial: "حـ",
    medial: "ـحـ",
    final: "ـح",
  },
  {
    letter: "خ",
    name: "Khāʾ",
    pronunciation: "wie ch in Bach",
    isolated: "خ",
    initial: "خـ",
    medial: "ـخـ",
    final: "ـخ",
  },
  {
    letter: "د",
    name: "Dāl",
    pronunciation: "wie d in Dach",
    isolated: "د",
    initial: "د",
    medial: "ـد",
    final: "ـد",
  },
  {
    letter: "ذ",
    name: "Dhāl",
    pronunciation: "wie th in this",
    isolated: "ذ",
    initial: "ذ",
    medial: "ـذ",
    final: "ـذ",
  },
  {
    letter: "ر",
    name: "Rāʾ",
    pronunciation: "wie ein gerolltes r",
    isolated: "ر",
    initial: "ر",
    medial: "ـر",
    final: "ـر",
  },
  {
    letter: "ز",
    name: "Zāy",
    pronunciation: "wie s in Sonne",
    isolated: "ز",
    initial: "ز",
    medial: "ـز",
    final: "ـز",
  },
  {
    letter: "س",
    name: "Sīn",
    pronunciation: "wie s in Salam",
    isolated: "س",
    initial: "سـ",
    medial: "ـسـ",
    final: "ـس",
  },
  {
    letter: "ش",
    name: "Shīn",
    pronunciation: "wie sch in Schule",
    isolated: "ش",
    initial: "شـ",
    medial: "ـشـ",
    final: "ـش",
  },
  {
    letter: "ص",
    name: "Ṣād",
    pronunciation: "ein dunkles, kräftiges s",
    isolated: "ص",
    initial: "صـ",
    medial: "ـصـ",
    final: "ـص",
  },
  {
    letter: "ض",
    name: "Ḍād",
    pronunciation: "ein dunkles, kräftiges d",
    isolated: "ض",
    initial: "ضـ",
    medial: "ـضـ",
    final: "ـض",
  },
  {
    letter: "ط",
    name: "Ṭāʾ",
    pronunciation: "ein dunkles, kräftiges t",
    isolated: "ط",
    initial: "طـ",
    medial: "ـطـ",
    final: "ـط",
  },
  {
    letter: "ظ",
    name: "Ẓāʾ",
    pronunciation: "ein dunkler th-Laut",
    isolated: "ظ",
    initial: "ظـ",
    medial: "ـظـ",
    final: "ـظ",
  },
  {
    letter: "ع",
    name: "ʿAyn",
    pronunciation: "ein tiefer Laut aus dem Hals",
    isolated: "ع",
    initial: "عـ",
    medial: "ـعـ",
    final: "ـع",
  },
  {
    letter: "غ",
    name: "Ghayn",
    pronunciation: "ein rauer Laut aus dem Hals",
    isolated: "غ",
    initial: "غـ",
    medial: "ـغـ",
    final: "ـغ",
  },
  {
    letter: "ف",
    name: "Fāʾ",
    pronunciation: "wie f in Fisch",
    isolated: "ف",
    initial: "فـ",
    medial: "ـفـ",
    final: "ـف",
  },
  {
    letter: "ق",
    name: "Qāf",
    pronunciation: "ein tiefes k aus dem Hals",
    isolated: "ق",
    initial: "قـ",
    medial: "ـقـ",
    final: "ـق",
  },
  {
    letter: "ك",
    name: "Kāf",
    pronunciation: "wie k in Kind",
    isolated: "ك",
    initial: "كـ",
    medial: "ـكـ",
    final: "ـك",
  },
  {
    letter: "ل",
    name: "Lām",
    pronunciation: "wie l in Lampe",
    isolated: "ل",
    initial: "لـ",
    medial: "ـلـ",
    final: "ـل",
  },
  {
    letter: "م",
    name: "Mīm",
    pronunciation: "wie m in Mond",
    isolated: "م",
    initial: "مـ",
    medial: "ـمـ",
    final: "ـم",
  },
  {
    letter: "ن",
    name: "Nūn",
    pronunciation: "wie n in Nase",
    isolated: "ن",
    initial: "نـ",
    medial: "ـنـ",
    final: "ـن",
  },
  {
    letter: "ه",
    name: "Hāʾ",
    pronunciation: "wie h in Haus",
    isolated: "ه",
    initial: "هـ",
    medial: "ـهـ",
    final: "ـه",
  },
  {
    letter: "و",
    name: "Wāw",
    pronunciation: "wie w, manchmal auch langes u",
    isolated: "و",
    initial: "و",
    medial: "ـو",
    final: "ـو",
  },
  {
    letter: "ي",
    name: "Yāʾ",
    pronunciation: "wie j, manchmal auch langes i",
    isolated: "ي",
    initial: "يـ",
    medial: "ـيـ",
    final: "ـي",
  },
];
